from .templates import (
    CATEGORIZATION_PROMPT,
    SENTIMENT_PROMPT,
    PRIORITY_PROMPT,
    DEPARTMENT_PROMPT,
    RESPONSE_PROMPT,
    ANALYTICS_SUMMARY_PROMPT,
)

__all__ = [
    "CATEGORIZATION_PROMPT",
    "SENTIMENT_PROMPT",
    "PRIORITY_PROMPT",
    "DEPARTMENT_PROMPT",
    "RESPONSE_PROMPT",
    "ANALYTICS_SUMMARY_PROMPT",
]
